name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/simple-ci.yml@main
    with:
      app-name: "Hello Backend"
      test-command: "npm test"
      sonar-project-key: coverage_demo_workflows
      sonar-host-url: https://sonarcloud.io
      sonar-organization: sudarshanhv
      enable-coverage: true

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/deploy.yml@main
    with:
      app-name: "sw-hello-backend-demo"
      environment: "staging"
